// This file is auto-generated by @hey-api/openapi-ts

export type ActionInfo = {
	user_id?: number | null;
	action: string;
	additional_data?: string | null;
	path_from?: string | null;
	path_to?: string | null;
};

export type HttpValidationError = {
	detail?: Array<ValidationError>;
};

export type User = {
	id: number;
	union_number?: string | null;
};

export type UserPatch = {
	union_number?: string | null;
	auth_user_id?: number | null;
};

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type WriteActionV1ActionPostData = {
	body: ActionInfo;
	headers?: {
		'user-agent'?: string | null;
	};
	path?: never;
	query?: never;
	url: '/v1/action';
};

export type WriteActionV1ActionPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WriteActionV1ActionPostError =
	WriteActionV1ActionPostErrors[keyof WriteActionV1ActionPostErrors];

export type WriteActionV1ActionPostResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type CreateUserV1UserPostData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/v1/user';
};

export type CreateUserV1UserPostResponses = {
	/**
	 * Successful Response
	 */
	200: User;
};

export type CreateUserV1UserPostResponse =
	CreateUserV1UserPostResponses[keyof CreateUserV1UserPostResponses];

export type PatchUserV1UserIdPatchData = {
	body: UserPatch;
	path: {
		id: number;
	};
	query?: never;
	url: '/v1/user/{id}';
};

export type PatchUserV1UserIdPatchErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type PatchUserV1UserIdPatchError =
	PatchUserV1UserIdPatchErrors[keyof PatchUserV1UserIdPatchErrors];

export type PatchUserV1UserIdPatchResponses = {
	/**
	 * Successful Response
	 */
	200: User;
};

export type PatchUserV1UserIdPatchResponse =
	PatchUserV1UserIdPatchResponses[keyof PatchUserV1UserIdPatchResponses];

export type ClientOptions = {
	baseUrl: `${string}://${string}/marketing` | (string & {});
};
