// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/marketing` | (string & {});
};

/**
 * ActionInfo
 */
export type ActionInfo = {
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Action
     */
    action: string;
    /**
     * Additional Data
     */
    additional_data?: string | null;
    /**
     * Path From
     */
    path_from?: string | null;
    /**
     * Path To
     */
    path_to?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: number;
    /**
     * Union Number
     */
    union_number?: string | null;
};

/**
 * UserPatch
 */
export type UserPatch = {
    /**
     * Union Number
     */
    union_number?: string | null;
    /**
     * Auth User Id
     */
    auth_user_id?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type WriteActionV1ActionPostData = {
    body: ActionInfo;
    headers?: {
        /**
         * User-Agent
         */
        'user-agent'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/action';
};

export type WriteActionV1ActionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WriteActionV1ActionPostError = WriteActionV1ActionPostErrors[keyof WriteActionV1ActionPostErrors];

export type WriteActionV1ActionPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateUserV1UserPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/user';
};

export type CreateUserV1UserPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateUserV1UserPostResponse = CreateUserV1UserPostResponses[keyof CreateUserV1UserPostResponses];

export type PatchUserV1UserIdPatchData = {
    body: UserPatch;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/v1/user/{id}';
};

export type PatchUserV1UserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchUserV1UserIdPatchError = PatchUserV1UserIdPatchErrors[keyof PatchUserV1UserIdPatchErrors];

export type PatchUserV1UserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type PatchUserV1UserIdPatchResponse = PatchUserV1UserIdPatchResponses[keyof PatchUserV1UserIdPatchResponses];
