// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { extensionsExtensionsGet, type Options, processConvertPost } from '../sdk.gen';
import type { ExtensionsExtensionsGetData, ProcessConvertPostData, ProcessConvertPostError, ProcessConvertPostResponse } from '../types.gen';

/**
 * Process
 *
 * Upload file to server. Takes extension to which the file will be converted and the file
 */
export const processConvertPostMutation = (options?: Partial<Options<ProcessConvertPostData>>): UseMutationOptions<ProcessConvertPostResponse, ProcessConvertPostError, Options<ProcessConvertPostData>> => {
    const mutationOptions: UseMutationOptions<ProcessConvertPostResponse, ProcessConvertPostError, Options<ProcessConvertPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await processConvertPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const extensionsExtensionsGetQueryKey = (options?: Options<ExtensionsExtensionsGetData>) => createQueryKey('extensionsExtensionsGet', options);

/**
 * Extensions
 */
export const extensionsExtensionsGetOptions = (options?: Options<ExtensionsExtensionsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await extensionsExtensionsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: extensionsExtensionsGetQueryKey(options)
    });
};
