// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/dating` | (string & {});
};

/**
 * Comment
 */
export type Comment = {
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Content
     */
    content: string;
    /**
     * Id
     */
    id: number;
    /**
     * Profile Id
     */
    profile_id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Content
     */
    content: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Profile
 */
export type Profile = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age: number;
    /**
     * Gender
     */
    gender: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Interests
     */
    interests?: string | null;
    /**
     * Contact
     */
    contact: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created Ts
     */
    created_ts: string;
    /**
     * Updated Ts
     */
    updated_ts: string;
};

/**
 * ProfileCreate
 */
export type ProfileCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age: number;
    /**
     * Gender
     */
    gender: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Interests
     */
    interests?: string | null;
    /**
     * Contact
     */
    contact: string;
};

/**
 * ProfileUpdate
 */
export type ProfileUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Gender
     */
    gender?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Interests
     */
    interests?: string | null;
    /**
     * Contact
     */
    contact?: string | null;
};

/**
 * ProfileWithComments
 */
export type ProfileWithComments = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age: number;
    /**
     * Gender
     */
    gender: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Interests
     */
    interests?: string | null;
    /**
     * Contact
     */
    contact: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created Ts
     */
    created_ts: string;
    /**
     * Updated Ts
     */
    updated_ts: string;
    /**
     * Comments
     */
    comments?: Array<Comment>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetProfilesProfilesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Min Age
         */
        min_age?: number | null;
        /**
         * Max Age
         */
        max_age?: number | null;
        /**
         * Gender
         */
        gender?: string | null;
    };
    url: '/profiles/';
};

export type GetProfilesProfilesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProfilesProfilesGetError = GetProfilesProfilesGetErrors[keyof GetProfilesProfilesGetErrors];

export type GetProfilesProfilesGetResponses = {
    /**
     * Response Get Profiles Profiles  Get
     *
     * Successful Response
     */
    200: Array<Profile>;
};

export type GetProfilesProfilesGetResponse = GetProfilesProfilesGetResponses[keyof GetProfilesProfilesGetResponses];

export type CreateProfileProfilesPostData = {
    body: ProfileCreate;
    path?: never;
    query?: never;
    url: '/profiles/';
};

export type CreateProfileProfilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProfileProfilesPostError = CreateProfileProfilesPostErrors[keyof CreateProfileProfilesPostErrors];

export type CreateProfileProfilesPostResponses = {
    /**
     * Successful Response
     */
    201: Profile;
};

export type CreateProfileProfilesPostResponse = CreateProfileProfilesPostResponses[keyof CreateProfileProfilesPostResponses];

export type DeleteProfileProfilesProfileIdDeleteData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: number;
    };
    query?: never;
    url: '/profiles/{profile_id}';
};

export type DeleteProfileProfilesProfileIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProfileProfilesProfileIdDeleteError = DeleteProfileProfilesProfileIdDeleteErrors[keyof DeleteProfileProfilesProfileIdDeleteErrors];

export type DeleteProfileProfilesProfileIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProfileProfilesProfileIdDeleteResponse = DeleteProfileProfilesProfileIdDeleteResponses[keyof DeleteProfileProfilesProfileIdDeleteResponses];

export type GetProfileProfilesProfileIdGetData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: number;
    };
    query?: never;
    url: '/profiles/{profile_id}';
};

export type GetProfileProfilesProfileIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProfileProfilesProfileIdGetError = GetProfileProfilesProfileIdGetErrors[keyof GetProfileProfilesProfileIdGetErrors];

export type GetProfileProfilesProfileIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProfileWithComments;
};

export type GetProfileProfilesProfileIdGetResponse = GetProfileProfilesProfileIdGetResponses[keyof GetProfileProfilesProfileIdGetResponses];

export type UpdateProfileProfilesProfileIdPutData = {
    body: ProfileUpdate;
    path: {
        /**
         * Profile Id
         */
        profile_id: number;
    };
    query?: never;
    url: '/profiles/{profile_id}';
};

export type UpdateProfileProfilesProfileIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileProfilesProfileIdPutError = UpdateProfileProfilesProfileIdPutErrors[keyof UpdateProfileProfilesProfileIdPutErrors];

export type UpdateProfileProfilesProfileIdPutResponses = {
    /**
     * Successful Response
     */
    200: Profile;
};

export type UpdateProfileProfilesProfileIdPutResponse = UpdateProfileProfilesProfileIdPutResponses[keyof UpdateProfileProfilesProfileIdPutResponses];

export type GetCommentsForProfileCommentsProfilesProfileIdCommentsGetData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/comments/profiles/{profile_id}/comments';
};

export type GetCommentsForProfileCommentsProfilesProfileIdCommentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCommentsForProfileCommentsProfilesProfileIdCommentsGetError = GetCommentsForProfileCommentsProfilesProfileIdCommentsGetErrors[keyof GetCommentsForProfileCommentsProfilesProfileIdCommentsGetErrors];

export type GetCommentsForProfileCommentsProfilesProfileIdCommentsGetResponses = {
    /**
     * Response Get Comments For Profile Comments Profiles  Profile Id  Comments Get
     *
     * Successful Response
     */
    200: Array<Comment>;
};

export type GetCommentsForProfileCommentsProfilesProfileIdCommentsGetResponse = GetCommentsForProfileCommentsProfilesProfileIdCommentsGetResponses[keyof GetCommentsForProfileCommentsProfilesProfileIdCommentsGetResponses];

export type CreateCommentForProfileCommentsProfilesProfileIdCommentsPostData = {
    body: CommentCreate;
    path: {
        /**
         * Profile Id
         */
        profile_id: number;
    };
    query?: never;
    url: '/comments/profiles/{profile_id}/comments';
};

export type CreateCommentForProfileCommentsProfilesProfileIdCommentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCommentForProfileCommentsProfilesProfileIdCommentsPostError = CreateCommentForProfileCommentsProfilesProfileIdCommentsPostErrors[keyof CreateCommentForProfileCommentsProfilesProfileIdCommentsPostErrors];

export type CreateCommentForProfileCommentsProfilesProfileIdCommentsPostResponses = {
    /**
     * Successful Response
     */
    201: Comment;
};

export type CreateCommentForProfileCommentsProfilesProfileIdCommentsPostResponse = CreateCommentForProfileCommentsProfilesProfileIdCommentsPostResponses[keyof CreateCommentForProfileCommentsProfilesProfileIdCommentsPostResponses];

export type DeleteCommentCommentsCommentsCommentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/comments/comments/{comment_id}';
};

export type DeleteCommentCommentsCommentsCommentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCommentCommentsCommentsCommentIdDeleteError = DeleteCommentCommentsCommentsCommentIdDeleteErrors[keyof DeleteCommentCommentsCommentsCommentIdDeleteErrors];

export type DeleteCommentCommentsCommentsCommentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCommentCommentsCommentsCommentIdDeleteResponse = DeleteCommentCommentsCommentsCommentIdDeleteResponses[keyof DeleteCommentCommentsCommentsCommentIdDeleteResponses];
