name: CI/CD Pipeline

on:
  release:
    types: [published]

env:
  REGISTRY: cr.yandex
  REGISTRY_ID: crpn9hemlidi718gq9es
  IMAGE_NAME: tvoi-ff
  YC_FOLDER_ID: sourcecraft

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}

      - name: Build and push Docker image
        env:
          CR_REGISTRY: ${{ env.REGISTRY_ID }}
          CR_REPOSITORY: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t ${{ env.REGISTRY }}/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker build -t ${{ env.REGISTRY }}/$CR_REGISTRY/$CR_REPOSITORY:latest .
          docker push ${{ env.REGISTRY }}/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
          docker push ${{ env.REGISTRY }}/$CR_REGISTRY/$CR_REPOSITORY:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v2
        env:
          CR_REGISTRY: ${{ env.REGISTRY_ID }}
          CR_REPOSITORY: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          folder-id: ${{ env.YC_FOLDER_ID }}
          vm-name: tvoi-ff
          vm-service-account-id: tvoi-ff
          docker-compose-path: './docker-compose.yaml'
